[package]
name = "niyah-studio"
version = "0.1.0"
description = "Local-first desktop shell for Niyah.Engine"
authors = ["Sulaiman Alshammari"]
edition = "2021"

[lib]
name = "niyah_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
